package-lock.json, package.json
- @nestjs/common 6.6.1 -> 7.6.18
- @nestjs/core 6.6.1 -> 7.6.18
- @nestjs/platform-express 6.6.1 -> 7.6.18
=> [Chore] @nestjs/common 버전 down

src/entities/Products.ts
- Products 엔티티의 color, otherColorList 타입을 string으로 변경
=> [Chore] Products Entity -> color 필드 타입 변경

src/common/decorators/user.decorator.ts, src/entities/Users.ts, src/entities/embedded/SuitedLens.ts, src/entities/embedded/WantedLens.ts, src/middlewares/auth.middleware.ts
- JWT Token을 통한 Request 유저 확인 에러 해결
- Users 엔티티 수정 (온보딩 정보 중복선택 여부에 따른 수정)
=> [Fix] JWT Token을 통한 Request 유저 확인 에러 해결

src/suggest/suggest.controller.ts, src/suggest/suggest.service.ts
- 쿼리스트링 인자를 통한 정렬 구현 (오름차순, 내림차순)
=> [Feat] 발견탭 상품 정렬 구현

src/entities/Products.ts, src/entities/embedded/WantedLens.ts, src/products/products.controller.ts, src/products/products.service.ts, src/suggest/suggest.controller.ts, src/suggest/suggest.service.ts
- Producs 엔티티 suggestList 필드 삭제 -> service단에서 구현하기로 변경.
- 상세페이지 API 구현 완료.
- Producs 엔티티티 changeCycleRange 필드 추가 -> 필터 검색 시 사용.
- 발견뷰 탭별 페이징 조회 API 구현 완료.
=> [merge] 상세페이지 API, 발견뷰 API 구현 완료

src/auth/auth.controller.ts, src/auth/auth.service.ts
- 카카오 로그인 (안드로이드) 구현
- 신규 유저 여부를 확인하기 위한 Boolean 값 넘겨주는 걸로 변경.
=> [Feat] Kakao Login For Android 구현 -> isNewUser Boolean 값 넘겨주기

src/app.controller.ts
- @UseGuard(new AuthGuard()) 추가
=> [Add] app.controller에 AuthGuard 적용

src/auth/auth.controller.ts, src/products/products.controller.ts, src/suggest/suggest.controller.ts, src/users/users.controller.ts
=> [Chore] 컨트롤러 라우팅 설정 변경 (/api) 추가

src/app.service.ts
=> [DEL] - unreachable code resolved

src/auth/auth.controller.ts
=> AuthKey 파일 S3 업로드

src/app.controller.ts, src/app.service.ts
=> [Del] 불필요한 UseGuard 제거

src/suggest/suggest.service.ts
- 클라이언트 요청에 따른 findSuggestProduct 함수 반환값 추가. (situation, season)
=> [Add] findSuggestProduct 함수에서 유저의 wearTime, season도 리턴 추가

src/app.controller.ts
- searchWindow controller 예외처리
=> [Fix] searchWindow controller 예외처리

src/app.controller.ts, src/products/products.controller.ts, src/suggest/suggest.controller.ts, src/suggest/suggest.service.ts, src/users/users.controller.ts
=> [Fix] 예외처리 코드 추가, 페이징 변수 수정

src/users/users.controller.ts
=> [Add] 온보딩 컨트롤러 Guard 추가

src/app.service.ts
- 페이징 skip 변수 수정
- reponse에 totalCount 추가 (클라이언트 요청)
=> [Fix] 검색/필터검색 API 페이징 변수, response 수정

src/app.service.ts
- 클라이언트 요청에 따른 findNewLens response 구조 수정
=> [Chore] 클라이언트 요청에 따른 findNewLens response 구조 수정

src/app.service.ts
=> [Add] 검색/필터검색 정렬 API 적용

src/suggest/suggest.service.ts
- suggestForSituation switch문 break 추가
=> [Fix] suggestForSituation switch문 break 추가

src/common/dto/suggest.response.dto.ts, src/suggest/suggest.service.ts
- 클라이언트 요청에 따른 발견탭 API response 구조 변경 -> totalPage 추가
=> [Chore] 클라이언트 요청에 따른 발견탭 API 요청 response 구조 변경 -> totalPage 추가
